Bootstrap: docker
From: rockylinux:9

%post
    yum install -y git wget gcc make openssl-devel readline-devel zlib-devel vim bzip2
    dnf -y group install "Development Tools"
    dnf -y install perl
    yum install -y epel-release
    #yum install -y ruby ruby-devel
    #gem install -v 4.3.3 jekyll
    #gem install -v 3.9.4 jekyll
    #gem install kramdown-parser-gfm
    mkdir -p /usr/local/src && cd /usr/local/src
    git clone https://github.com/snic-nsc/nscjekyllsetup.git
    cd nscjekyllsetup && git checkout 'new_jekyll'
    bash presetup.sh
    bash setup.sh
